apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trio
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            short: dev
            ns: dev
          - cluster: in-cluster
            short: qa
            ns: qa
          - cluster: in-cluster
            short: staging
            ns: staging

  template:
    metadata:
      name: trioapp-{{short}}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.'
        codefresh.io/product: trio
        codefresh.io/app-group: trio
    spec:
      destination:
        name: '{{cluster}}'
        namespace: '{{ns}}'
      source:
        path: 'manifests/trio-app/aperture-{{short}}'
        repoURL: 'https://github.com/dmaizel/DevOps'
        targetRevision: main
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
