apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-synced-apps-app2-qa
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - list:
        elements:
        - name: 'kc-v-qa'
          namespace: multi-app-test
  template:
    metadata:
      name: multi-synced-apps-app2-2-qa
    spec:
      destination:
        name: "{{name}}"
        namespace: "{{namespace}}"
      source:
        path: manifests/multi-apps/aperture-qa/app2
        repoURL: 'https://github.com/dmaizel/DevOps'
        targetRevision: HEAD
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true